services:
#    platform.example:
#        class: PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

# src/OC/PlatformBundle/Resources/config/services.yml
    oc_platform.antispam:
        class: PlatformBundle\Antispam\Antispam